name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      # - run: pip install -r requirements.txt
      - run : yes | sam delete --stack-name sam-app-action-01 --region us-east-1 --no-prompts
      # - run: y | sam delete --stack-name dev-stack --region us-east-1
      # - run: y | sam delete --stack-name prod-stack --region us-east-1
      # - run: pip install aws-sam-cli
      # - run: sam build
      # - run: sam deploy --region us-east-1 --no-confirm-changeset
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.BETA_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.BETA_ACCESS_KEY }}
