name: Deploy to AWS

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      # - run: pip install -r requirements.txt
      - run: pip install aws-sam-cli
      - run: sam build
      - run: sam deploy --no-confirm-changeset --stack-name dev-stack --region us-east-1  # Specify dev stack and region
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.BETA_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.BETA_ACCESS_KEY }}

  deploy-prod:
    needs: deploy-dev  # Ensure dev deployment is successful before prod
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: sam deploy --no-confirm-changeset --stack-name prod-stack --region us-east-1  # Specify prod stack and region
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.BETA_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.BETA_ACCESS_KEY }}
